import { ChangeEvent, useMemo, useRef, useState } from "react";
import { Navigate } from "react-router-dom";
import Konva from "konva";
import { toast } from "sonner";
import { ChevronDown, ChevronUp, Copy, Download, Eye, EyeOff, Grid3X3, ImagePlus, Lock, LockOpen, Redo2, Save, Trash2, Undo2, Upload } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AvatarStage } from "@/avatar-system/composer/AvatarStage";
import { AvatarLayer, AvatarLayerType, LAYER_TYPES } from "@/avatar-system/composer/composer.types";
import { bindAssetToComposition, hasLoadedAsset, inspectPng, parseComposition, serializeComposition, sortLayers, splitLayer, uid } from "@/avatar-system/composer/composer.utils";
import { useComposerState } from "@/avatar-system/composer/useComposerState";
import { AURIS_AVATAR_STANDARD_V1 as STANDARD } from "@/avatar-system/standards/avatar-standard-v1";

const download = (content: string, filename: string, type: string) => { const a = document.createElement("a"); a.href = type === "image/png" ? content : URL.createObjectURL(new Blob([content], { type })); a.download = filename; a.click(); if (type !== "image/png") URL.revokeObjectURL(a.href); };
const filename = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export default function AdminAvatarComposer() {
  const { isAdmin, loading } = useAuth(); const state = useComposerState(); const stageRef = useRef<Konva.Stage|null>(null);
  const uploadRef = useRef<HTMLInputElement>(null); const importRef = useRef<HTMLInputElement>(null); const uploadMode = useRef<"replace"|"new">("new");
  const [assetType, setAssetType] = useState<AvatarLayerType>("generic"); const [zoom, setZoom] = useState(.42); const [guides, setGuides] = useState(true); const [preview, setPreview] = useState(false); const [background, setBackground] = useState<"checker"|"dark"|"light">("checker");
  const selected = state.composition.layers.find(l => l.id === state.selectedId); const ordered = useMemo(() => sortLayers(state.composition.layers), [state.composition.layers]);
  if (loading) return <div>Carregando…</div>; if (!isAdmin) return <Navigate to="/app" replace />;

  const chooseLocalPng = () => { if (selected && hasLoadedAsset(selected)) uploadMode.current = window.confirm("Replace asset in selected layer?\n\nOK: replace selected asset\nCancel: add as new layer") ? "replace" : "new"; else uploadMode.current = selected ? "replace" : "new"; uploadRef.current?.click(); };
  const addFiles = async (event: ChangeEvent<HTMLInputElement>) => { const files=Array.from(event.target.files??[]); for (let index=0;index<files.length;index++) try { const file=files[index]; const info=await inspectPng(file); const target=index===0?selected:undefined; let mode:"replace"|"new"|"bootPair"=index===0?uploadMode.current:"new"; if(target?.type==="boots"&&target.equipmentId&&window.confirm("Assign as boot pair?\n\nOK: populate Left and Right render parts\nCancel: assign only the selected boot")) mode="bootPair"; if(mode==="replace"&&target?.sourceKind==="local"&&target.source.startsWith("blob:")) URL.revokeObjectURL(target.source); state.commit(composition=>bindAssetToComposition(composition,target?.id??null,info,mode)); if(info.warning)toast.warning(info.warning); else toast.success(mode==="new"?"Nova layer criada.":mode==="bootPair"?"PNG atribuído ao par de botas.":"PNG atribuído à layer selecionada."); } catch(error){toast.error(error instanceof Error?error.message:"Falha ao carregar PNG.");} event.target.value=""; };
  const importJson = async (event: ChangeEvent<HTMLInputElement>) => { const file=event.target.files?.[0]; if (!file) return; try { const parsed=parseComposition(await file.text()); parsed.layers=parsed.layers.map(layer => layer.sourceKind === "local" || layer.source.startsWith("blob:") ? {...layer,missing:true,warning:"Asset local precisa ser recarregado."} : layer); state.loadComposition(parsed); toast.success("Layout importado."); } catch(error) { toast.error(error instanceof Error?error.message:"JSON inválido."); } event.target.value=""; };
  const exportPng = () => { const stage=stageRef.current; if(!stage)return; const hidden:Konva.Node[]=[]; stage.find("Transformer").forEach(n=>{if(n.isVisible()){n.hide();hidden.push(n);}}); stage.find(".editor-guide").forEach(n=>{if(n.isVisible()){n.hide();hidden.push(n);}}); stage.batchDraw(); const data=stage.toDataURL({pixelRatio:1/zoom,mimeType:"image/png"}); hidden.forEach(n=>n.show()); stage.batchDraw(); download(data,`${state.composition.avatarId}_${filename(state.composition.presetName)}_v1.png`,"image/png"); };
  const moveSelected = (delta:number) => { if(!selected)return; const index=ordered.findIndex(l=>l.id===selected.id); state.reorder(selected.id,index+delta); };
  const duplicate = () => selected && state.addLayers([{...selected,id:uid(),name:`${selected.name} copy`,transform:{...selected.transform,x:selected.transform.x+10,y:selected.transform.y+10},zIndex:selected.zIndex+1}]);
  const align = (kind:"h"|"v"|"ground"|"reset") => selected && state.updateLayer(selected.id, layer => ({...layer,transform:kind==="reset"?{...layer.transform,x:0,y:0,xNormalized:0,yNormalized:0,scaleX:1,scaleY:1,rotation:0,opacity:1}:{...layer.transform,x:kind==="h"?512-(layer.nativeWidth??0)*layer.transform.scaleX/2:layer.transform.x,y:kind==="v"?768-(layer.nativeHeight??0)*layer.transform.scaleY/2:kind==="ground"?STANDARD.guides.groundLine.y-(layer.trimBounds?.height??layer.nativeHeight??0)*layer.transform.scaleY:layer.transform.y}}));
  const split = () => { if(!selected)return; state.commit(c=>({...c,layers:[...c.layers.filter(l=>l.id!==selected.id),...splitLayer(selected)]})); state.setSelectedId(null); };
  const save = () => { const name=window.prompt("Nome do preset",state.composition.presetName); if(name){state.savePreset(name);toast.success("Preset salvo neste navegador.");} };
  const loadPreset = (id:string) => { const preset=state.presets().find(p=>p.id===id); if(preset)state.loadComposition(preset.composition); };

  return <div className="-m-4 md:-m-6 min-h-[calc(100vh-3.5rem)] bg-slate-950 text-slate-100 flex flex-col">
    <div className="border-b border-slate-700 bg-slate-900 p-2 flex flex-wrap items-center gap-2">
      <div className="mr-2"><div className="font-display font-bold">Auris Avatar Composer</div><div className="text-[10px] text-slate-400">Standard v1 · 1024 × 1536</div></div>
      <Select value={state.composition.presetId} onValueChange={loadPreset}><SelectTrigger className="w-48 h-8 bg-slate-800"><SelectValue placeholder={state.composition.presetName}/></SelectTrigger><SelectContent>{state.presets().map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select>
      <Select value={assetType} onValueChange={v=>setAssetType(v as AvatarLayerType)}><SelectTrigger className="w-36 h-8 bg-slate-800"><SelectValue/></SelectTrigger><SelectContent>{LAYER_TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select>
      <Button size="sm" onClick={chooseLocalPng}><ImagePlus className="w-4 h-4"/> Add local PNG</Button><input ref={uploadRef} hidden type="file" accept="image/png" multiple onChange={addFiles}/>
      <Button size="sm" variant="secondary" onClick={()=>importRef.current?.click()}><Upload className="w-4 h-4"/> Import JSON</Button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={importJson}/>
      <Button size="sm" variant="secondary" onClick={save}><Save className="w-4 h-4"/> Save preset</Button>
      <Button size="icon" variant="ghost" disabled={!state.canUndo} onClick={state.undo}><Undo2 className="w-4 h-4"/></Button><Button size="icon" variant="ghost" disabled={!state.canRedo} onClick={state.redo}><Redo2 className="w-4 h-4"/></Button>
      <Button size="sm" variant={preview?"default":"secondary"} onClick={()=>setPreview(v=>!v)}><Eye className="w-4 h-4"/> Preview</Button><Button size="sm" variant={guides?"default":"secondary"} onClick={()=>setGuides(v=>!v)}><Grid3X3 className="w-4 h-4"/> Guides</Button>
      <Button size="sm" variant="secondary" onClick={()=>download(serializeComposition(state.composition),`${filename(state.composition.presetId)}.json`,"application/json")}><Download className="w-4 h-4"/> JSON</Button><Button size="sm" onClick={exportPng}><Download className="w-4 h-4"/> PNG</Button>
    </div>
    <div className="flex flex-1 min-h-0">
      <aside className="w-64 shrink-0 border-r border-slate-700 bg-slate-900 flex flex-col"><div className="p-3 border-b border-slate-700 font-semibold flex justify-between"><span>Layers ({ordered.length})</span><span className="text-xs text-slate-400">z-order</span></div><div className="overflow-auto flex-1 p-2 space-y-1">{[...ordered].reverse().map((layer,index)=><div key={layer.id} draggable onDragStart={e=>e.dataTransfer.setData("text/layer",layer.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/layer");state.reorder(id,ordered.length-1-index);}} onClick={()=>state.setSelectedId(layer.id)} className={`p-2 rounded border cursor-pointer ${layer.id===state.selectedId?"border-sky-400 bg-sky-950":"border-slate-700 bg-slate-800"}`}><div className="flex items-center gap-2"><button onClick={e=>{e.stopPropagation();state.updateLayer(layer.id,{visible:!layer.visible});}}>{layer.visible?<Eye className="w-4 h-4"/>:<EyeOff className="w-4 h-4 text-slate-500"/>}</button><div className="w-9 h-9 bg-slate-700 rounded grid place-items-center overflow-hidden">{!layer.missing?<img src={layer.source} className="max-w-full max-h-full"/>:<span className="text-red-400 text-xs">!</span>}</div><div className="min-w-0 flex-1"><div className="text-sm truncate">{layer.name}</div><div className="text-[10px] text-slate-400">{layer.type} · z {layer.zIndex}{layer.renderPartId?` · ${layer.renderPartId}`:""}</div></div><button onClick={e=>{e.stopPropagation();state.updateLayer(layer.id,{locked:!layer.locked});}}>{layer.locked?<Lock className="w-4 h-4"/>:<LockOpen className="w-4 h-4 text-slate-500"/>}</button></div>{layer.warning&&<div className="text-[10px] text-amber-300 mt-1">{layer.warning}</div>}</div>)}</div>
        <div className="p-2 border-t border-slate-700 grid grid-cols-5 gap-1"><Button size="icon" variant="ghost" onClick={()=>moveSelected(1)}><ChevronUp/></Button><Button size="icon" variant="ghost" onClick={()=>moveSelected(-1)}><ChevronDown/></Button><Button size="icon" variant="ghost" onClick={duplicate}><Copy/></Button><Button size="icon" variant="ghost" onClick={split} title="Split Left / Right">↔</Button><Button size="icon" variant="destructive" onClick={()=>selected&&state.removeLayer(selected.id)}><Trash2/></Button></div>
      </aside>
      <main className="flex-1 min-w-0 overflow-auto bg-slate-800 p-6"><div className="flex items-center gap-2 mb-3 sticky left-0"><Button size="sm" variant="secondary" onClick={()=>setZoom(z=>Math.max(.1,z-.1))}>−</Button><span className="text-xs w-12 text-center">{Math.round(zoom*100)}%</span><Button size="sm" variant="secondary" onClick={()=>setZoom(z=>Math.min(1,z+.1))}>+</Button><Button size="sm" variant="secondary" onClick={()=>setZoom(.42)}>Fit</Button><Button size="sm" variant="secondary" onClick={()=>setZoom(1)}>100%</Button><Select value={background} onValueChange={v=>setBackground(v as typeof background)}><SelectTrigger className="w-32 h-8 bg-slate-900"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="checker">Checker</SelectItem><SelectItem value="dark">Dark</SelectItem><SelectItem value="light">Light</SelectItem></SelectContent></Select></div><div className="w-max mx-auto shadow-2xl"><AvatarStage composition={state.composition} selectedId={state.selectedId} scale={zoom} background={background} guides={guides} preview={preview} onSelect={id=>state.setSelectedId(id||null)} onLayerChange={layer=>state.updateLayer(layer.id,layer,true)} onStart={state.beginTransaction} onEnd={state.endTransaction} stageRef={stageRef}/></div></main>
      <aside className="w-72 shrink-0 border-l border-slate-700 bg-slate-900 overflow-auto p-3">{selected?<Properties layer={selected} onChange={(patch)=>state.updateLayer(selected.id,patch) } align={align}/>:<p className="text-sm text-slate-400">Selecione uma layer.</p>}</aside>
    </div><div className="border-t border-slate-700 bg-slate-900 px-3 py-1 text-xs text-slate-400">{selected?`${selected.name} · X ${selected.transform.x.toFixed(1)} · Y ${selected.transform.y.toFixed(1)} · normalized ${selected.transform.xNormalized.toFixed(5)}, ${selected.transform.yNormalized.toFixed(5)}`:"Nenhuma layer selecionada"}</div>
  </div>;
}

function Properties({layer,onChange,align}:{layer:AvatarLayer;onChange:(p:Partial<AvatarLayer>)=>void;align:(k:"h"|"v"|"ground"|"reset")=>void}) { const transform=(key:keyof AvatarLayer["transform"],value:number)=>onChange({transform:{...layer.transform,[key]:value}}); return <div className="space-y-3"><h2 className="font-semibold">Properties</h2><Field label="Name"><Input value={layer.name} onChange={e=>onChange({name:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Type"><Select value={layer.type} onValueChange={v=>onChange({type:v as AvatarLayerType})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{LAYER_TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></Field><Field label="Placement"><Select value={layer.placementType} onValueChange={v=>onChange({placementType:v as "body"|"scene"})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="body">body</SelectItem><SelectItem value="scene">scene</SelectItem></SelectContent></Select></Field></div><Field label="Equipment ID"><Input value={layer.equipmentId??""} onChange={e=>onChange({equipmentId:e.target.value||undefined})}/></Field><Field label="Render part ID"><Input value={layer.renderPartId??""} onChange={e=>onChange({renderPartId:e.target.value||undefined})}/></Field><div className="grid grid-cols-2 gap-2">{(["x","y","scaleX","scaleY","rotation","opacity"] as const).map(key=><NumberField key={key} label={key} value={layer.transform[key]} step={key==="opacity"?.05:key.startsWith("scale")?.01:1} onChange={v=>transform(key,v)}/>)}<NumberField label="zIndex" value={layer.zIndex} onChange={v=>onChange({zIndex:v})}/></div><div className="text-xs text-slate-400">Normalized: {layer.transform.xNormalized.toFixed(8)}, {layer.transform.yNormalized.toFixed(8)}</div><div className="text-xs text-slate-400">Native: {layer.nativeWidth??"?"} × {layer.nativeHeight??"?"}<br/>Trim: {layer.trimBounds?`${layer.trimBounds.x}, ${layer.trimBounds.y}, ${layer.trimBounds.width} × ${layer.trimBounds.height}`:"not inspected"}<br/>Source: {layer.source}</div><div className="grid grid-cols-2 gap-2"><Button size="sm" variant="secondary" onClick={()=>align("h")}>Center H</Button><Button size="sm" variant="secondary" onClick={()=>align("v")}>Center V</Button><Button size="sm" variant="secondary" onClick={()=>align("ground")}>Ground</Button><Button size="sm" variant="destructive" onClick={()=>align("reset")}>Reset</Button></div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div><Label className="text-xs text-slate-400">{label}</Label>{children}</div>; }
function NumberField({label,value,onChange,step=1}:{label:string;value:number;onChange:(v:number)=>void;step?:number}) { return <Field label={label}><Input type="number" step={step} value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))}/></Field>; }
